services:
  mcpdoc-daemon:
    build:
      context: .
      dockerfile: Containerfile
    container_name: mcpdoc-daemon
    ports:
      - "8080:8080"
    volumes:
      - "./config:/config:z,ro"
    restart: unless-stopped
    environment:
      - MCPDOC_LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
